<?php

/**
 * @file
 * Contains ewp_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function ewp_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_core module.
    case 'help.page.ewp_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('EWP core data types and utilities') . '</p>';
      $output .= '<p>' . t('Learn more at ') . '<a href="https://developers.erasmuswithoutpaper.eu" target="_blank">developers.erasmuswithoutpaper.eu</a>.</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_element_info_alter().
 */
function ewp_core_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'ewp_core/toolbar';
  }
}

/**
 * Implements hook_theme().
 */
function ewp_core_theme() {
  return [
    'ewp_core' => [
      'render element' => 'children',
    ],
    'ewp_string_lang_default' => [],
    'ewp_multiline_lang_default' => [],
    'ewp_http_lang_default' => [],
  ];
}

/**
 * Get ISO 639-1 language codes.
 *
 * Get associative array of two-letter language codes from a source file.
 *
 * @return array $options
 */
function ewp_core_get_language_codes() {
  $source_file = 'includes/language_codes_iso639-1.inc';
  include $source_file;

  $options = [];
  foreach ($language_codes as $top => $array) {
    $group = [];
    foreach ($array as $key => $value) {
      $group[$key] = $value;
    }
    $options[$top] = $group;
  }

  return $options;
}

/**
 * Get ISO/IEC 5218 human sexes.
 *
 * Get associative array of single digit human sex codes from a source file.
 *
 * @return array $options
 */
function ewp_core_get_human_sexes() {
  $source_file = 'includes/human_sexes_isoiec5218.inc';
  include $source_file;

  $options = [];
  foreach ($human_sexes as $key => $value) {
    $options[$key] = $value;
  }

  return $options;
}

/**
 * Get CEFR levels.
 *
 * Get associative array of CEFR levels from a source file.
 *
 * @return array $options
 */
function ewp_core_get_cefr_levels() {
  $source_file = 'includes/cefr_levels.inc';
  include $source_file;

  $options = [];
  foreach ($cefr_levels as $key => $value) {
    $options[$key] = $value;
  }

  return $options;
}

/**
 * Get EQF levels.
 *
 * Get associative array of single digit EQF levels from a source file.
 *
 * @return array $options
 */
function ewp_core_get_eqf_levels() {
  $source_file = 'includes/eqf_levels.inc';
  include $source_file;

  $options = [];
  foreach ($eqf_levels as $key => $value) {
    $options[$key] = $value;
  }

  return $options;
}

/**
 * Implements hook_form_alter
 *
 */
function ewp_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Any necessary changes here
}
