<?php

/**
 * @file
 * Contains ewp_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function ewp_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_core module.
    case 'help.page.ewp_core':
      $url = 'https://developers.erasmuswithoutpaper.eu';
      $link = Link::fromTextAndUrl($url, Url::fromUri($url, [
        'attributes' => [
          'target' => '_blank',
        ],
      ]));
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('EWP core data types and utilities') . '</p>';
      $output .= '<p>' . t('Learn more at @link', [
        '@link' => $link->toString(),
      ]) . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_element_info_alter().
 */
function ewp_core_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'ewp_core/toolbar';
  }
}

/**
 * Implements hook_theme().
 */
function ewp_core_theme() {
  return [
    'ewp_ascii_identifier_default' => [
      'variables' => [
        'value' => NULL,
      ],
    ],
    'ewp_cefr_level_default' => [
      'variables' => [
        'value' => NULL,
        'parent' => NULL,
      ],
    ],
    'ewp_eqf_level_default' => [
      'variables' => [
        'value' => NULL,
      ],
    ],
    'ewp_gender_code_default' => [
      'variables' => [
        'value' => NULL,
      ],
    ],
    'ewp_https_default' => [
      'variables' => [
        'url' => NULL,
        'title' => NULL,
      ],
    ],
    'ewp_http_lang_default' => [
      'variables' => [
        'url' => NULL,
        'title' => NULL,
        'langcode' => NULL,
        'langname' => NULL,
      ],
    ],
    'ewp_multiline_lang_default' => [
      'variables' => [
        'multiline' => NULL,
        'langcode' => NULL,
        'langname' => NULL,
      ],
    ],
    'ewp_string_lang_default' => [
      'variables' => [
        'string' => NULL,
        'langcode' => NULL,
        'langname' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function ewp_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Any necessary changes here.
}

/**
 * Implements hook_field_info_alter().
 *
 * @todo Remove once minimum version supported is at least 10.2.0.
 */
function ewp_core_field_info_alter(array &$info): void {
  // Allow module to work with older versions of Drupal.
  if (\version_compare(\Drupal::VERSION, '10.1.9999', '<')) {
    $info['ascii_identifier']['category'] = t("EWP");
    $info['cefr_level']['category'] = t("EWP select options");
    $info['eqf_level']['category'] = t("EWP select options");
    $info['gender_code']['category'] = t("EWP select options");
    $info['ewp_http_lang']['category'] = t("EWP");
    $info['ewp_https']['category'] = t("EWP");
    $info['ewp_multiline_lang']['category'] = t("EWP");
    $info['ewp_string_lang']['category'] = t("EWP");
  }
}
