# Schema for the configuration of the ASCII Printable Identifier field type.
field.value.ascii_identifier:
  type: mapping
  label: Default value
  mapping:
    value:
      type: string
      label: Identifier
      constraints:
        Regex:
          pattern: '/^[ -~]+$/'
          message: 'ASCII printable characters only.'

field.storage_settings.ascii_identifier:
  type: mapping
  label: 'ASCII Printable Identifier settings'
  mapping:
    max_length:
      type: integer
      label: 'Maximum length'
    case_sensitive:
      type: boolean
      label: 'Case sensitive'
    is_ascii:
      type: boolean
      label: 'Contains US ASCII characters only'

field.widget.settings.ascii_identifier_default:
  type: mapping
  label: 'Text field display format settings'
  mapping:
    size:
      type: integer
      label: 'Size of textfield'
      constraints:
        Range:
          min: 0
    placeholder:
      type: label
      label: 'Placeholder'

# Schema for the configuration of the CEFR level field type.
field.value.cefr_level:
  type: mapping
  label: Default value
  mapping:
    value:
      type: string
      label: Value
      constraints:
        Regex:
          pattern: '/^[ABC][12]$/'

# Schema for the configuration of the EQF level field type.
field.value.eqf_level:
  type: mapping
  label: Default value
  mapping:
    value:
      type: integer
      label: Value
      constraints:
        Range:
          min: 1
          max: 8

# Schema for the configuration of the Gender code field type.
field.value.gender_code:
  type: mapping
  label: Default value
  mapping:
    value:
      type: integer
      label: Value
      constraints:
        Choice:
          - 0
          - 1
          - 2
          - 9

# Schema for the configuration of the HTTPS field type.
field.value.ewp_https:
  type: mapping
  label: 'Default value'
  mapping:
    attributes:
      type: mapping
      label: 'Link attributes'
      mapping:
        title:
          type: label
          label: 'Link text'
    uri:
      type: string
      label: 'URL'
      constraints:
        Regex:
          pattern: '/^https:\/\//'
    title:
      type: label
      label: 'Link text'
    options:
      type: mapping
      label: 'Link options'
      mapping:
        query:
          type: sequence
          label: 'URL query key value pairs'
          sequence:
            type: string
        fragment:
          type: string
          label: 'URL fragment'
        absolute:
          type: boolean
          label: 'Whether to force the output to be an absolute link (beginning with http: or https:)'
        https:
          type: boolean
          label: 'Whether to force this URL to point to a secure location (beginning with https:)'
        attributes:
          type: sequence
          label: 'Link attributes'
          sequence:
            type: string

field.field_settings.ewp_https:
  type: mapping
  label: 'Link settings'
  mapping:
    title:
      type: integer
      label: 'Allow link text'
      constraints:
        Choice:
          - 0
          - 1
          - 2
    link_type:
      type: integer
      label: 'Allowed link type'
      constraints:
        Choice:
          - 0x01
          - 0x10
          - 0x11

field.widget.settings.ewp_https_default:
  type: mapping
  label: 'Link format settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
      constraints:
        Length:
          min: 0
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
      constraints:
        Length:
          min: 0

# Schema for the configuration of the HTTP with optional lang field type.
field.value.ewp_http_lang:
  type: mapping
  label: Default value
  mapping:
    attributes:
      type: mapping
      label: 'Link attributes'
      mapping:
        title:
          type: label
          label: 'Link text'
    uri:
      type: label
      label: URI
      constraints:
        NotBlank: []
    lang:
      type: string
      label: Language
      constraints:
        ValidLanguageTag: ~
    title:
      type: label
      label: 'Link text'
    options:
      type: mapping
      label: 'Link options'
      mapping:
        query:
          type: sequence
          label: 'URL query key value pairs'
          sequence:
            type: string
        fragment:
          type: string
          label: 'URL fragment'
        absolute:
          type: boolean
          label: 'Whether to force the output to be an absolute link (beginning with http: or https:)'
        https:
          type: boolean
          label: 'Whether to force this URL to point to a secure location (beginning with https:)'
        attributes:
          type: sequence
          label: 'Link attributes'
          sequence:
            type: string

field.field_settings.ewp_http_lang:
  type: mapping
  label: 'Link settings'
  mapping:
    title:
      type: integer
      label: 'Allow link text'
      constraints:
        Choice:
          - 0
          - 1
          - 2
    link_type:
      type: integer
      label: 'Allowed link type'
      constraints:
        Choice:
          - 0x01
          - 0x10
          - 0x11

field.widget.settings.ewp_http_lang_default:
  type: mapping
  label: 'Link format settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
      constraints:
        Length:
          min: 0
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
      constraints:
        Length:
          min: 0

# Schema for the configuration of the Language tag field type.
field.value.ewp_lang:
  type: mapping
  label: Default value
  mapping:
    lang:
      type: string
      label: Language
      constraints:
        ValidLanguageTag: ~

# Schema for the configuration of the Multiline string with optional lang field type.
field.value.ewp_multiline_lang:
  type: mapping
  label: Default value
  mapping:
    multiline:
      type: string
      label: Text
      constraints:
        NotBlank: []
    lang:
      type: string
      label: Language
      constraints:
        ValidLanguageTag: ~

field.widget.settings.ewp_multiline_lang_default:
  type: mapping
  label: 'Textarea display format settings'
  mapping:
    rows:
      type: integer
      label: 'Rows'
      constraints:
        Range:
          min: 1
    placeholder:
      type: label
      label: 'Placeholder'

# Schema for the configuration of the String with optional lang field type.
field.value.ewp_string_lang:
  type: mapping
  label: Default value
  mapping:
    string:
      type: string
      label: String
      constraints:
        NotBlank: []
    lang:
      type: string
      label: Language
      constraints:
        ValidLanguageTag: ~

field.storage_settings.ewp_string_lang:
  type: mapping
  label: 'String with optional lang settings'
  mapping:
    max_length:
      type: integer
      label: 'Maximum length'

field.widget.settings.ewp_string_lang_default:
  type: mapping
  label: 'Text field display format settings'
  mapping:
    size:
      type: integer
      label: 'Size of textfield'
      constraints:
        Range:
          min: 0
    placeholder:
      type: label
      label: 'Placeholder'

# Schema for the configuration files of the EWP core module.
ewp_core.settings:
  type: config_object
  label: 'EWP core settings'
  mapping:
    lang_primary_group_label:
      type: string
      translatable: true
      label: 'Primary language group label'
      constraints:
        NotBlank: []
    lang_primary_list:
      type: sequence
      label: 'Primary language options'
      constraints:
        NotBlank: []
      sequence:
        type: string
        translatable: true
        constraints:
          LanguageTagOption: ~
    lang_secondary_group_label:
      type: string
      translatable: true
      label: 'Secondary language group label'
      constraints:
        NotBlank: []
    lang_secondary_list:
      type: sequence
      label: 'Secondary language options'
      constraints:
        NotBlank: []
      sequence:
        type: string
        translatable: true
        constraints:
          LanguageTagOption: ~
